
server:
  port: 8080

spring:
  application:
    name: eureka-server

  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
